
import casual_shirt from '../assets/casual_shirt.jpeg';
import casual_shirt_blue from "../assets/casual_shirt_blue.png";
import casual_shirt_black from "../assets/casual_shirt_black.png";

const products = [
{
  id: 1,
  name: "Men's Casual Shirt",
  price: 1299,
  discountPercentage: 15,
  image: casual_shirt,
  category: "Men",
  subcategory: "Shirts",
  description: "Comfortable cotton casual shirt.",
  gender: "Men",
  fabric: "Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
  reviews: 9.1,  

  // New field for colors
  colors: [
  { name: "Rust", code: "#B7410E", image: casual_shirt },
  { name: "Blue", code: "#1E90FF", image: casual_shirt_blue },
  { name: "Black", code: "#000000", image: casual_shirt_black }
  
],

  // New field for extra info
  extraInfo: [
    "🔄 10 Days Return & Exchange",
    "💵 Cash on Delivery Available",
    "🚚 Free Delivery",
    "🏷️ Top Brand",
    "✅ Secure Transaction"
  ]
},

  {
    id: 2,
    name: "Men's Formal Shirt",
    price: 1599,
    discountPercentage: 20,
    image: "formal-shirt.jpg",
    category: "Men",
    subcategory: "Shirts",
    description: "Slim-fit formal shirt for office wear.",
    gender: "Men",
    fabric: "Cotton Blend",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL", "XXL"]
  },
  {
    id: 3,
    name: "Men's T-Shirt",
    price: 799,
    discountPercentage: 10,
    image: "tshirt.jpg",
    category: "Men",
    subcategory: "T-Shirts",
    description: "Soft and breathable casual t-shirt.",
    gender: "Men",
    fabric: "Poly-Cotton",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 4,
    name: "Men's Polo T-Shirt",
    price: 899,
    discountPercentage: 25,
    image: "polo.jpg",
    category: "Men",
    subcategory: "T-Shirts",
    description: "Classic polo with collar design.",
    gender: "Men",
    fabric: "Cotton",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 5,
    name: "Men's Jeans",
    price: 1999,
    discountPercentage: 30,
    image: "jeans.jpg",
    category: "Men",
    subcategory: "Pants",
    description: "Stylish slim-fit jeans.",
    gender: "Men",
    fabric: "Denim",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["28", "30", "32", "34", "36"]
  },
  {
    id: 6,
    name: "Men's Chinos",
    price: 1799,
    discountPercentage: 15,
    image: "chinos.jpg",
    category: "Men",
    subcategory: "Pants",
    description: "Comfortable cotton chinos.",
    gender: "Men",
    fabric: "Cotton",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["28", "30", "32", "34", "36"]
  },
  {
    id: 7,
    name: "Men's Kurta",
    price: 1499,
    discountPercentage: 20,
    image: "kurta.jpg",
    category: "Men",
    subcategory: "Ethnic Wear",
    description: "Elegant kurta for festive occasions.",
    gender: "Men",
    fabric: "Cotton Silk",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 8,
    name: "Men's Nehru Jacket",
    price: 2499,
    discountPercentage: 25,
    image: "nehru-jacket.jpg",
    category: "Men",
    subcategory: "Ethnic Wear",
    description: "Classic Nehru jacket for traditional look.",
    gender: "Men",
    fabric: "Silk Blend",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 9,
    name: "Men's Blazer",
    price: 3999,
    discountPercentage: 15,
    image: "blazer.jpg",
    category: "Men",
    subcategory: "Suits & Blazers",
    description: "Slim-fit blazer for formal events.",
    gender: "Men",
    fabric: "Polyester Blend",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["38", "40", "42", "44"]
  },
  {
    id: 10,
    name: "Men's Sherwani Set",
    price: 4999,
    discountPercentage: 20,
    image: "sherwani.jpg",
    category: "Men",
    subcategory: "Ethnic Wear",
    description: "A beautiful sherwani for weddings.",
    gender: "Men",
    fabric: "Silk",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 11,
    name: "Women's Casual Dress",
    price: 1599,
    discountPercentage: 25,
    image: "casual-dress.jpg",
    category: "Women",
    subcategory: "Dresses",
    description: "Stylish cotton casual dress.",
    gender: "Women",
    fabric: "Cotton",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 12,
    name: "Women's Party Dress",
    price: 2599,
    discountPercentage: 30,
    image: "party-dress.jpg",
    category: "Women",
    subcategory: "Dresses",
    description: "Elegant party dress for special occasions.",
    gender: "Women",
    fabric: "Polyester",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L"]
  },
  {
    id: 13,
    name: "Women's Kurti",
    price: 999,
    discountPercentage: 15,
    image: "kurti.jpg",
    category: "Women",
    subcategory: "Ethnic Wear",
    description: "Comfortable printed cotton kurti.",
    gender: "Women",
    fabric: "Cotton",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 14,
    name: "Women's Saree",
    price: 2999,
    discountPercentage: 20,
    image: "saree.jpg",
    category: "Women",
    subcategory: "Ethnic Wear",
    description: "Beautiful silk saree for weddings.",
    gender: "Women",
    fabric: "Silk",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["Free Size"]
  },
  {
    id: 15,
    name: "Women's Lehenga",
    price: 4999,
    discountPercentage: 25,
    image: "lehenga.jpg",
    category: "Women",
    subcategory: "Ethnic Wear",
    description: "Designer lehenga for festive wear.",
    gender: "Women",
    fabric: "Silk Blend",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L"]
  },
  {
    id: 16,
    name: "Women's Tops",
    price: 799,
    discountPercentage: 10,
    image: "top.jpg",
    category: "Women",
    subcategory: "Tops",
    description: "Trendy casual tops for daily wear.",
    gender: "Women",
    fabric: "Polyester",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 17,
    name: "Women's Trousers",
    price: 1299,
    discountPercentage: 15,
    image: "trousers.jpg",
    category: "Women",
    subcategory: "Pants",
    description: "Formal trousers for office wear.",
    gender: "Women",
    fabric: "Polyester Blend",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["28", "30", "32", "34"]
  },
  {
    id: 18,
    name: "Women's Jeans",
    price: 1599,
    discountPercentage: 20,
    image: "womens-jeans.jpg",
    category: "Women",
    subcategory: "Pants",
    description: "Slim-fit stretchable jeans.",
    gender: "Women",
    fabric: "Denim",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["28", "30", "32", "34"]
  },
  {
    id: 19,
    name: "Women's Shrug",
    price: 1199,
    discountPercentage: 10,
    image: "shrug.jpg",
    category: "Women",
    subcategory: "Outerwear",
    description: "Lightweight shrug for layering.",
    gender: "Women",
    fabric: "Polyester",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L"]
  },
  {
    id: 20,
    name: "Women's Blazer",
    price: 2499,
    discountPercentage: 30,
    image: "womens-blazer.jpg",
    category: "Women",
    subcategory: "Outerwear",
    description: "Formal blazer for professional look.",
    gender: "Women",
    fabric: "Polyester Blend",
    netQuantity: "1",
    countryOfOrigin: "India",
    sizes: ["S", "M", "L", "XL"]
  },
 {
  id: 21,
  name: "Women's Party Wear Gown",
  price: 3499,
  discountPercentage: 18,
  image: "party_gown.jpg",
  category: "Women",
  subcategory: "Party Wear",
  description: "An elegant floor-length gown perfect for parties and receptions.",
  gender: "Women",
  fabric: "Georgette",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id: 22,
  name: "Women's Ethnic Saree",
  price: 2499,
  discountPercentage: 15,
  image: "ethnic_saree.jpg",
  category: "Women",
  subcategory: "Ethnic Wear",
  description: "Traditional silk saree with intricate zari work.",
  gender: "Women",
  fabric: "Silk",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["Free Size"]
},
{
  id: 23,
  name: "Women's Cotton Kurti",
  price: 1299,
  discountPercentage: 10,
  image: "cotton_kurti.jpg",
  category: "Women",
  subcategory: "Casual Wear",
  description: "Lightweight cotton kurti for everyday comfort.",
  gender: "Women",
  fabric: "Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id: 24,
  name: "Women's Designer Lehenga",
  price: 5999,
  discountPercentage: 22,
  image: "designer_lehenga.jpg",
  category: "Women",
  subcategory: "Ethnic Wear",
  description: "Designer lehenga choli with heavy embroidery work.",
  gender: "Women",
  fabric: "Net",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L"]
},
{
  id: 25,
  name: "Men's Formal Suit",
  price: 5499,
  discountPercentage: 20,
  image: "formal_suit.jpg",
  category: "Men",
  subcategory: "Formal Wear",
  description: "Classic black formal suit with tailored fit.",
  gender: "Men",
  fabric: "Polyester Blend",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL"]
},
{
  id: 26,
  name: "Men's Casual Blazer",
  price: 2799,
  discountPercentage: 12,
  image: "casual_blazer.jpg",
  category: "Men",
  subcategory: "Casual Wear",
  description: "Stylish blazer suitable for semi-formal events.",
  gender: "Men",
  fabric: "Cotton Blend",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL"]
},
{
  id: 27,
  name: "Men's Polo T-Shirt",
  price: 799,
  discountPercentage: 8,
  image: "polo_tshirt.jpg",
  category: "Men",
  subcategory: "Casual Wear",
  description: "Comfortable polo t-shirt for casual outings.",
  gender: "Men",
  fabric: "Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id: 28,
  name: "Men's Sports Tracksuit",
  price: 1999,
  discountPercentage: 14,
  image: "sports_tracksuit.jpg",
  category: "Men",
  subcategory: "Sportswear",
  description: "Breathable and flexible tracksuit for workouts.",
  gender: "Men",
  fabric: "Polyester",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL"]
},
{
  id: 29,
  name: "Kids' Party Dress",
  price: 1499,
  discountPercentage: 18,
  image: "kids_party_dress.jpg",
  category: "Kids",
  subcategory: "Party Wear",
  description: "Cute and colorful party dress for girls.",
  gender: "Girls",
  fabric: "Net",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["2-4Y", "4-6Y", "6-8Y"]
},
{
  id: 30,
  name: "Kids' Ethnic Kurta Pajama",
  price: 1299,
  discountPercentage: 12,
  image: "kids_kurta_pajama.jpg",
  category: "Kids",
  subcategory: "Ethnic Wear",
  description: "Traditional kurta pajama set for boys.",
  gender: "Boys",
  fabric: "Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["2-4Y", "4-6Y", "6-8Y"]
},
{
  id: 31,
  name: "Kids' Winter Jacket",
  price: 1899,
  discountPercentage: 16,
  image: "kids_winter_jacket.jpg",
  category: "Kids",
  subcategory: "Winter Wear",
  description: "Warm and cozy jacket for cold days.",
  gender: "Unisex",
  fabric: "Wool Blend",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["2-4Y", "4-6Y", "6-8Y"]
},
{
  id: 32,
  name: "Kids' Sports Tracksuit",
  price: 1599,
  discountPercentage: 10,
  image: "kids_tracksuit.jpg",
  category: "Kids",
  subcategory: "Sportswear",
  description: "Comfortable tracksuit for active kids.",
  gender: "Unisex",
  fabric: "Polyester",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["2-4Y", "4-6Y", "6-8Y"]
},
{
  id: 33,
  name: "Women's Winter Sweater",
  price: 1899,
  discountPercentage: 14,
  image: "womens_sweater.jpg",
  category: "Women",
  subcategory: "Winter Wear",
  description: "Cozy knitted sweater for winter fashion.",
  gender: "Women",
  fabric: "Wool",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id: 34,
  name: "Women's Denim Jacket",
  price: 2299,
  discountPercentage: 15,
  image: "denim_jacket.jpg",
  category: "Women",
  subcategory: "Casual Wear",
  description: "Classic blue denim jacket for a trendy look.",
  gender: "Women",
  fabric: "Denim",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id: 35,
  name: "Men's Leather Jacket",
  price: 3999,
  discountPercentage: 20,
  image: "leather_jacket.jpg",
  category: "Men",
  subcategory: "Winter Wear",
  description: "Stylish leather jacket for a rugged look.",
  gender: "Men",
  fabric: "Leather",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL"]
},
{
  id: 36,
  name: "Men's Hoodie",
  price: 1499,
  discountPercentage: 10,
  image: "mens_hoodie.jpg",
  category: "Men",
  subcategory: "Winter Wear",
  description: "Comfortable fleece hoodie for casual wear.",
  gender: "Men",
  fabric: "Fleece",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL"]
},
{
  id: 37,
  name: "Women's Sports Leggings",
  price: 999,
  discountPercentage: 8,
  image: "sports_leggings.jpg",
  category: "Women",
  subcategory: "Sportswear",
  description: "Stretchable leggings for gym and yoga.",
  gender: "Women",
  fabric: "Polyester Blend",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L"]
},
{
  id: 38,
  name: "Women's Tank Top",
  price: 699,
  discountPercentage: 5,
  image: "tank_top.jpg",
  category: "Women",
  subcategory: "Casual Wear",
  description: "Lightweight tank top for daily comfort.",
  gender: "Women",
  fabric: "Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L"]
},
{
  id: 39,
  name: "Men's Gym Shorts",
  price: 799,
  discountPercentage: 6,
  image: "gym_shorts.jpg",
  category: "Men",
  subcategory: "Sportswear",
  description: "Breathable gym shorts for intense workouts.",
  gender: "Men",
  fabric: "Polyester",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL"]
},
{
  id: 40,
  name: "Men's Running Shoes",
  price: 2499,
  discountPercentage: 18,
  image: "running_shoes.jpg",
  category: "Men",
  subcategory: "Footwear",
  description: "Lightweight running shoes for performance and comfort.",
  gender: "Men",
  fabric: "Mesh",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["7", "8", "9", "10"]
},
{
  id: 41,
  name: "Women's Sneakers",
  price: 2199,
  discountPercentage: 16,
  image: "womens_sneakers.jpg",
  category: "Women",
  subcategory: "Footwear",
  description: "Trendy sneakers for everyday wear.",
  gender: "Women",
  fabric: "Canvas",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["5", "6", "7", "8"]
},
{
  id: 42,
  name: "Men's Leather Formal Shoes",
  price: 2999,
  discountPercentage: 20,
  image: "formal_shoes.jpg",
  category: "Men",
  subcategory: "Footwear",
  description: "Elegant leather shoes for formal occasions.",
  gender: "Men",
  fabric: "Leather",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["7", "8", "9", "10"]
},
{
  id: 43,
  name: "Kids' School Shoes",
  price: 1299,
  discountPercentage: 10,
  image: "school_shoes.jpg",
  category: "Kids",
  subcategory: "Footwear",
  description: "Durable and comfortable school shoes for kids.",
  gender: "Unisex",
  fabric: "Synthetic",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["2", "3", "4", "5"]
},
{
  id: 44,
  name: "Women's High Heels",
  price: 2599,
  discountPercentage: 18,
  image: "high_heels.jpg",
  category: "Women",
  subcategory: "Footwear",
  description: "Stylish high heels for parties and formal wear.",
  gender: "Women",
  fabric: "Synthetic Leather",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["5", "6", "7", "8"]

},
// New Arrivals
{
  id: 45,
  name: "Men's Slim Fit Blazer",
  price: 4499,
  discountPercentage: 10,
  image: "slim_fit_blazer.jpg",
  category: "New Arrivals",
  description: "Elegant slim fit blazer for formal events and parties.",
  gender: "Men",
  fabric: "Polyester Blend",
  netQuantity: "1 Piece",
  countryOfOrigin: "India",
  sizes: ["38", "40", "42", "44"]
},
{
  id: 46,
  name: "Women's Floral Maxi Dress",
  price: 2999,
  discountPercentage: 12,
  image: "floral_maxi_dress.jpg",
  category: "New Arrivals",
  description: "Lightweight maxi dress with floral prints, perfect for summer.",
  gender: "Women",
  fabric: "Chiffon",
  netQuantity: "1 Piece",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id:47,
  name: "Unisex Sports Sneakers",
  price: 1999,
  discountPercentage: 15,
  image: "sports_sneakers.jpg",
  category: "New Arrivals",
  description: "Comfortable sports sneakers for daily wear and workouts.",
  gender: "Unisex",
  fabric: "Mesh",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["6", "7", "8", "9", "10"]
},
{
  id: 48,
  name: "Men's Casual Polo T-Shirt",
  price: 1299,
  discountPercentage: 8,
  image: "casual_polo_tshirt.jpg",
  category: "New Arrivals",
  description: "Casual polo t-shirt with breathable cotton fabric.",
  gender: "Men",
  fabric: "Cotton",
  netQuantity: "1 Piece",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id: 49,
  name: "Women's Designer Handbag",
  price: 3499,
  discountPercentage: 20,
  image: "designer_handbag.jpg",
  category: "New Arrivals",
  description: "Spacious handbag with premium leather finish.",
  gender: "Women",
  fabric: "PU Leather",
  netQuantity: "1 Piece",
  countryOfOrigin: "India",
  sizes: []
},

// Sale
{
  id: 50,
  name: "Men's Denim Jacket",
  price: 2499,
  discountPercentage: 25,
  image: "denim_jacket.jpg",
  category: "New Arrivals",
  description: "Classic denim jacket with rugged style.",
  gender: "Men",
  fabric: "Denim",
  netQuantity: "1 Piece",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id: 51,
  name: "Women's Ankle Boots",
  price: 2999,
  discountPercentage: 30,
  image: "ankle_boots.jpg",
  category: "New Arrivals",
  description: "Stylish ankle boots with a comfortable fit.",
  gender: "Women",
  fabric: "Suede Leather",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["5", "6", "7", "8"]
},
{
  id: 51,
  name: "Men's Formal Trousers",
  price: 1999,
  discountPercentage: 35,
  image: "formal_trousers.jpg",
  category: "New Arrivals",
  description: "Slim-fit formal trousers for office wear.",
  gender: "Men",
  fabric: "Polyester Viscose",
  netQuantity: "1 Piece",
  countryOfOrigin: "India",
  sizes: ["30", "32", "34", "36", "38"]
},
{
  id: 52,
  name: "Women's Winter Sweater",
  price: 1799,
  discountPercentage: 40,
  image: "winter_sweater.jpg",
  category: "New Arrivals",
  description: "Cozy knitted sweater perfect for chilly days.",
  gender: "Women",
  fabric: "Wool Blend",
  netQuantity: "1 Piece",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
},
{
  id: 53,
  name: "Men's Leather Wallet",
  price: 999,
  discountPercentage: 45,
  image: "leather_wallet.jpg",
  category: "New Arrivals",
  description: "Compact and stylish leather wallet with multiple compartments.",
  gender: "Men",
  fabric: "Genuine Leather",
  netQuantity: "1 Piece",
  countryOfOrigin: "India",
  sizes: []
},
{
  id: 54,
  name: "Men's Slim Fit Jeans",
  price: 2299,
  discountPercentage: 25,
  image: "slim-jeans.jpg",
  category: "Men",
  subcategory: "Pants",
  description: "Stylish slim-fit jeans with stretch fabric for all-day comfort.",
  gender: "Men",
  fabric: "Denim",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["30", "32", "34", "36", "38"]
},
{
  id: 55,
  name: "Women's Floral Maxi Dress",
  price: 2999,
  discountPercentage: 30,
  image: "floral-maxi-dress.jpg",
  category: "Women",
  subcategory: "Dresses",
  description: "Elegant floral print maxi dress perfect for evening outings.",
  gender: "Women",
  fabric: "Georgette",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["XS", "S", "M", "L", "XL"]
},
{
  id: 56,
  name: "Men's Leather Formal Shoes",
  price: 3499,
  discountPercentage: 15,
  image: "leather-formal-shoes.jpg",
  category: "Men",
  subcategory: "Shoes",
  description: "Classic lace-up leather shoes for office and formal occasions.",
  gender: "Men",
  fabric: "Genuine Leather",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["6", "7", "8", "9", "10", "11"]
},
{
  id: 57,
  name: "Women's Ethnic Kurta Set",
  price: 2599,
  discountPercentage: 35,
  image: "ethnic-kurta-set.jpg",
  category: "Women",
  subcategory: "Ethnic Wear",
  description: "Beautiful kurta with palazzo and dupatta, ideal for festive occasions.",
  gender: "Women",
  fabric: "Rayon",
  netQuantity: "1 Set",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL", "XXL"]
},
{
  id: 58,
  name: "Kid's Cartoon Printed T-shirt",
  price: 799,
  discountPercentage: 20,
  image: "cartoon-tshirt.jpg",
  category: "Kids",
  subcategory: "Tops",
  description: "Cute cartoon print T-shirt for kids, perfect for daily wear.",
  gender: "Unisex",
  fabric: "Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["2-3Y", "3-4Y", "5-6Y", "7-8Y"]
},
{
  id: 59,
  name: "Men's Sports Running Shoes",
  price: 2799,
  discountPercentage: 28,
  image: "running-shoes.jpg",
  category: "Men",
  subcategory: "Shoes",
  description: "Lightweight and durable running shoes for active lifestyle.",
  gender: "Men",
  fabric: "Mesh & Rubber",
  netQuantity: "1 Pair",
  countryOfOrigin: "India",
  sizes: ["6", "7", "8", "9", "10"]
},
{
  id: 60,
  name: "Women's Handbag - Leatherette",
  price: 1999,
  discountPercentage: 40,
  image: "women-handbag.jpg",
  category: "Women",
  subcategory: "Accessories",
  description: "Trendy handbag with spacious compartments for daily use.",
  gender: "Women",
  fabric: "Leatherette",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["One Size"]
}
,{
  id: 61,
  name: "Men's Casual T-Shirt",
  price: 799,
  discountPercentage: 15,
  image: "casual-tshirt.jpg",
  category: "Men",
  subcategory: "T-Shirts",
  description: "Classic round-neck cotton casual t-shirt.",
  gender: "Men",
  fabric: "100% Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL", "XXL"]
},
{
  id: 62,
  name: "Men's Slim Fit Jeans",
  price: 2199,
  discountPercentage: 25,
  image: "slimfit-jeans.jpg",
  category: "Men",
  subcategory: "Jeans",
  description: "Blue washed slim fit denim jeans.",
  gender: "Men",
  fabric: "Denim",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["28", "30", "32", "34", "36", "38"]
},
{
  id: 63,
  name: "Men's Formal Blazer",
  price: 4999,
  discountPercentage: 30,
  image: "formal-blazer.jpg",
  category: "Men",
  subcategory: "Blazers",
  description: "Single-breasted slim-fit formal blazer.",
  gender: "Men",
  fabric: "Polyester Viscose Blend",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["36", "38", "40", "42", "44"]
},
{
  id: 64,
  name: "Men's Hoodie Sweatshirt",
  price: 1899,
  discountPercentage: 20,
  image: "hoodie-sweatshirt.jpg",
  category: "Men",
  subcategory: "Sweatshirts",
  description: "Comfortable fleece-lined hoodie sweatshirt.",
  gender: "Men",
  fabric: "Cotton Fleece",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL", "XXL"]
},
{
  id: 65,
  name: "Men's Cargo Pants",
  price: 2499,
  discountPercentage: 18,
  image: "cargo-pants.jpg",
  category: "Men",
  subcategory: "Pants",
  description: "Multi-pocket slim-fit cargo pants for casual wear.",
  gender: "Men",
  fabric: "Cotton Twill",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["30", "32", "34", "36", "38"]
},
{
  id: 66,
  name: "Men's Leather Jacket",
  price: 6999,
  discountPercentage: 35,
  image: "leather-jacket.jpg",
  category: "Men",
  subcategory: "Jackets",
  description: "Premium quality biker-style leather jacket.",
  gender: "Men",
  fabric: "Genuine Leather",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL", "XXL"]
},
{
  id: 67,
  name: "Men's Polo T-Shirt",
  price: 1299,
  discountPercentage: 22,
  image: "polo-tshirt.jpg",
  category: "Men",
  subcategory: "T-Shirts",
  description: "Solid color short-sleeve polo t-shirt.",
  gender: "Men",
  fabric: "Cotton Pique",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL", "XXL"]
},
{
  id: 68,
  name: "Men's Slim Fit Casual Shirt",
  price: 1299,
  discountPercentage: 25,
  image: "mens-casual-slimfit-shirt.jpg",
  category: "Men",
  subcategory: "Shirts",
  description: "Slim fit cotton casual shirt with full sleeves.",
  gender: "Men",
  fabric: "100% Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL", "XXL"]
},
{
  id: 69,
  name: "Men's Checked Casual Shirt",
  price: 1499,
  discountPercentage: 30,
  image: "mens-checked-shirt.jpg",
  category: "Men",
  subcategory: "Shirts",
  description: "Trendy checked shirt with button-down collar.",
  gender: "Men",
  fabric: "Cotton Blend",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL", "XXL"]
},
{
  id: 70,
  name: "Men's Formal Solid Shirt",
  price: 1699,
  discountPercentage: 20,
  image: "mens-formal-solid-shirt.jpg",
  category: "Men",
  subcategory: "Shirts",
  description: "Classic solid color formal shirt for office wear.",
  gender: "Men",
  fabric: "Poly Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL", "XXL"]
},
{
  id: 71,
  name: "Men's Denim Shirt",
  price: 1799,
  discountPercentage: 15,
  image: "mens-denim-shirt.jpg",
  category: "Men",
  subcategory: "Shirts",
  description: "Casual denim shirt with full sleeves.",
  gender: "Men",
  fabric: "Denim",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["M", "L", "XL"]
},
{
  id: 72,
  name: "Men's Striped Casual Shirt",
  price: 1399,
  discountPercentage: 28,
  image: "mens-striped-shirt.jpg",
  category: "Men",
  subcategory: "Shirts",
  description: "Trendy striped cotton casual shirt.",
  gender: "Men",
  fabric: "100% Cotton",
  netQuantity: "1",
  countryOfOrigin: "India",
  sizes: ["S", "M", "L", "XL"]
}
];
export default products;
